### ISSUE TITLE
Error when testing the installation 'SeqRecord'

### ISSUE THREAD

**Issue by tiagobrc** [YosefLab/BRAPeS#2]
Hi, thanks for this amazing software!.

I want to test the BCR reconstruction of BRAPeS but I am kind of stuck in the installation test. Could you please take a look at the output to see if something is wrong? I don't understand why this error is showing up.

Thanks

```
2019-10-29 12:07:32.466758 Working on: ERR1467921
2019-10-29 12:07:32.492118 Pre-processing heavy chain
2019-10-29 12:07:32.515206 Did not find any V-J reads, searching for V-C and J-C reads:
Added 139 unmapped reads to the reads file
2019-10-29 12:07:42.920253 Pre-processing kappa chain
Traceback (most recent call last):
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 2155, in <module>
    args.Fr)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 52, in runBCRpipe
    hvr_path, genome)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 285, in runSingleCell
    unDictKappa = analyzeChain(fastaDict, vdjDict, output, bam, unmapped, idNameDict, bases, 'K', strand, NolowQ, top, byExp, readOverlap, downsample, organism, Hminus, Kminus, Lminus)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 1440, in analyzeChain
    junctionSegs = makeJunctionFile(bam, chain, output, bases, vdjDict, fastaDict, idNameDict, top, byExp, readOverlap, organism)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 1473, in makeJunctionFile
    junctionSegs = writeJunctions(vjReads,outName, bases, fastaDict, idNameDict, cSeq, top, vjCounts, byExp)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 1986, in writeJunctions
    pairCountDict[record] = curCont
TypeError: unhashable type: 'SeqRecord'
```

**Comment by shakea02** [comment]
Hello,
Thank you for your interest in BRAPeS! I added changes to BRAPeS that should fix this issue. Could you pull the new version and let me know if you still get this error?

Best,
Shaked

**Comment by tiagobrc** [comment]
Hi,

Thank you so much for your response!!

The problem disappeared indeed. But a new issue appeared.

It seems to be an issue with my glibc compiler. That's a tough one to solve in this server.

Thanks for your help!

```

2019-10-31 11:56:35.739137 Working on: ERR1467921
2019-10-31 11:56:35.770980 Pre-processing heavy chain
2019-10-31 11:56:35.793876 Did not find any V-J reads, searching for V-C and J-C reads:
Added 139 unmapped reads to the reads file
2019-10-31 11:56:45.921126 Pre-processing kappa chain
Added 957 unmapped reads to the reads file
2019-10-31 11:56:56.738079 Pre-processing lambda chain
2019-10-31 11:56:56.754041 Did not find any V-J reads, searching for V-C and J-C reads:
Added 222 unmapped reads to the reads file
2019-10-31 11:57:06.754495 Reconstructing heavy chains
/ru-auth/local/home/trezende/localPrograms/BRAPeS//vdj.alignment.bcr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /ru-auth/local/home/trezende/localPrograms/BRAPeS//vdj.alignment.bcr)
2019-10-31 11:57:06.760834 Reconstructing kappa chains
/ru-auth/local/home/trezende/localPrograms/BRAPeS//vdj.alignment.bcr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /ru-auth/local/home/trezende/localPrograms/BRAPeS//vdj.alignment.bcr)
2019-10-31 11:57:06.766358 Reconstructing lambda chains
/ru-auth/local/home/trezende/localPrograms/BRAPeS//vdj.alignment.bcr: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /ru-auth/local/home/trezende/localPrograms/BRAPeS//vdj.alignment.bcr)
2019-10-31 11:57:06.771920 Creating full BCR sequences
Traceback (most recent call last):
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 2157, in <module>
    args.Fr)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 52, in runBCRpipe
    hvr_path, genome)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 305, in runSingleCell
    createTCRFullOutput(fastaDict, tcrF, fullTcrFileHeavy, bases, idNameDict, cSeq, cName, cId, oneSide)
  File "/ru-auth/local/home/trezende/localPrograms/BRAPeS/brapes.py", line 1250, in createTCRFullOutput
    tcrF = open(tcr, 'rU')
IOError: [Errno 2] No such file or directory: '/ru-auth/local/home/trezende/localPrograms/BRAPeS/Example/proc_data/ERR1467921/BRAPeS_out.reconstructed.junctions.heavy.fa'

```
